services:

  mongodb:
    image: mongo:latest
    restart: always
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
  
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - ./mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"


  node:
    build: 
      context: ./node
      dockerfile: Dockerfile.node
    container_name: node
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./node:/app
      - /app/node_modules
    depends_on:
        - mysql
        - mongodb
    environment:
      - NODE_ENV=${NODE_ENV}

  vuetify:
    build: 
      context: ./vuetify
      dockerfile: Dockerfile.vuetify
    container_name: vuetify
    restart: always
    ports:
        - "3001:3001"
    volumes:
      - ./vuetify:/app
      - /app/node_modules
    depends_on:
      - node

