services:

  mongodb:
    image: mongo:latest
    restart: always
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 5s
      timeout: 3s
      retries: 5
  
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 5

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"


  node:
    build: 
      context: ./node
      dockerfile: Dockerfile.node
    container_name: node
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./node:/app
      - /app/node_modules
    depends_on:
        mysql:
          condition: service_healthy
        #mongodb:
          #condition: service_healthy
    environment:
      - NODE_ENV=${NODE_ENV}

  vuetify:
    build: 
      context: ./vuetify
      dockerfile: Dockerfile.vuetify
    container_name: vuetify
    restart: always
    ports:
        - "3001:3001"
    volumes:
      - ./vuetify:/app
      - /app/node_modules
    depends_on:
      - node

